echo "file '/etc/motd' do" > default.rb
echo "  content 'MOTD file generated by Chef'" >> default.rb
echo "end" >> default.rb

( curl -L https://www.getchef.com/chef/install.sh | bash -s -- -P chefdk -v 1.2.22 ) &> /tmp/install.log
